[package]
authors       = ["Havunen <sampo.kivisto@live.fi>"]
description   = "SWC plugin for InfernoJS."
documentation = "https://github.com/infernojs/swc-plugin-inferno"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "MIT"
name          = "swc-plugin-inferno"
repository    = "https://github.com/infernojs/swc-plugin-inferno.git"
version       = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
bench = false

[features]
concurrent = ["rayon"]
default    = ["serde-impl"]
serde-impl = ["serde"]

[dependencies]
base64    = "0.21.3"
dashmap   = "5.5.1"
indexmap  = "2.0.0"
once_cell = "1.18.0"
rayon     = { version = "1.7.0", optional = true }
serde     = { version = "1.0.188", features = ["derive"], optional = true }
sha-1     = "=0.10.0"

swc_core = { version = "0.82.1", features = [
    "swc_atoms",
    "swc_common",
    "swc_ecma_ast",
    "swc_ecma_utils",
    "ecma_plugin_transform",
    "ecma_utils",
    "ecma_visit",
    "ecma_ast",
    "common",
] }
swc_ecma_parser            = { version = "0.139.0" }
swc_config                 = { version = "0.1.7" }

[dev-dependencies]
swc_ecma_codegen            = { version = "0.144.0" }
swc_ecma_transforms_compat  = { version = "0.158.0" }
swc_ecma_transforms_module  = { version = "0.175.0" }
swc_ecma_transforms_testing = { version = "0.135.0" }
swc_ecma_transforms         = { version = "0.223.0" }
testing                     = { version = "0.34.0"  }
