[package]
authors       = ["Havunen <sampo.kivisto@live.fi>"]
description   = "SWC plugin for InfernoJS."
documentation = "https://github.com/infernojs/swc-plugin-inferno"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "MIT"
name          = "swc-plugin-inferno"
repository    = "https://github.com/infernojs/swc-plugin-inferno.git"
version       = "0.0.16"

[lib]
crate-type = ["cdylib", "rlib"]
bench = false

[features]
concurrent = ["rayon"]
default    = ["serde-impl"]
serde-impl = ["serde"]

[profile.release]
# This removes more dead code
codegen-units = 1
lto = true
# Optimize for size
opt-level = "s"
# Optimize for performance, this is default, so you don't need to specify it
# opt-level = "z"

# Strip debug symbols
strip = "symbols"

[dependencies]
base64    = "0.21.5"
dashmap   = "5.5.3"
indexmap  = "2.1.0"
once_cell = "1.19.0"
rayon     = { version = "1.8.0", optional = true }
serde     = { version = "1.0.193", features = ["derive"], optional = true }
sha-1     = "=0.10.1"

swc_core = { version = "0.87.10", features = [
    "swc_atoms",
    "swc_common",
    "swc_ecma_ast",
    "swc_ecma_utils",
    "ecma_plugin_transform",
    "ecma_utils",
    "ecma_visit",
    "ecma_ast",
    "common",
] }
swc_ecma_parser            = { version = "0.141.34" }
swc_config                 = { version = "0.1.9" }

[dev-dependencies]
swc_ecma_codegen            = { version = "0.146.48" }
swc_ecma_transforms_compat  = { version = "0.161.7" }
swc_ecma_transforms_module  = { version = "0.178.7" }
swc_ecma_transforms_testing = { version = "0.138.5" }
swc_ecma_transforms         = { version = "0.227.7" }
testing                     = { version = "0.35.14"  }
