[package]
authors       = ["Havunen <sampo.kivisto@live.fi>"]
description   = "SWC plugin for InfernoJS."
documentation = "https://rustdoc.swc.rs/swc_ecma_transforms_inferno/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "MIT"
name          = "swc_ecma_transforms_inferno"
repository    = "https://github.com/swc-project/swc.git"
version       = "0.0.1"

[lib]
bench = false

[features]
concurrent = ["rayon"]
default    = ["serde-impl"]
serde-impl = ["serde"]

[dependencies]
base64    = "0.21.3"
dashmap   = "5.5.1"
indexmap  = "2.0.0"
once_cell = "1.18.0"
rayon     = { version = "1.7.0", optional = true }
serde     = { version = "1.0.188", features = ["derive"], optional = true }
sha-1     = "=0.10.0"

swc_atoms                  = { version = "0.5.9" }
swc_common                 = { version = "0.32.0" }
swc_config                 = { version = "0.1.7"  }
swc_ecma_ast               = { version = "0.109.0" }
swc_ecma_parser            = { version = "0.139.0" }
swc_ecma_transforms_base   = { version = "0.132.0" }
swc_ecma_transforms_macros = { version = "0.5.2" }
swc_ecma_utils             = { version = "0.122.0" }
swc_ecma_visit             = { version = "0.95.0" }

[dev-dependencies]
swc_ecma_codegen            = { version = "0.144.0" }
swc_ecma_transforms_compat  = { version = "0.158.0" }
swc_ecma_transforms_module  = { version = "0.175.0" }
swc_ecma_transforms_testing = { version = "0.135.0" }
testing                     = { version = "0.34.0" }
